import type { Expression } from '../../types.js'
import type { ResponsePlan, ResponsePlanLine } from './response-plan.js'
import { SESSION_RESPONSE_PLANS } from './response-plan-data-session.js'
import {
  RECOMMENDATION_CANCEL_PLANS,
  RECOMMENDATION_RANDOM_REQUEST_PLANS,
  RECOMMENDATION_TAIL_PLANS,
} from './response-plan-data-recommendation.js'

function line(text: string, expression: Expression): ResponsePlanLine {
  return { text, expression }
}

function uniformLines(expression: Expression, texts: readonly string[]): ResponsePlanLine[] {
  return texts.map((text) => line(text, expression))
}

export const RAW_RESPONSE_PLANS: readonly ResponsePlan[] = [
  {
    id: 'karua.small-talk.general-chat',
    speaker: 'karua',
    intent: 'small_talk',
    request: 'general-chat',
    blocks: {
      answer: [
        line('이야기가 아직 끝날 표정은 아니네요.', 'talk'),
        line('아, 그런 쪽이었군요.', 'talk'),
        line('아, 그런 얘기였네요.', 'talk'),
        line('음, 거기서 이야기가 한 번 꺾이네요.', 'talk'),
        line('아, 그 말은 잔향이 좀 남네요.', 'thinking'),
        line('손님은 참 다양한 이야기를 하시네요. 듣는 재미가 있어요.', 'smirk'),
        line('그 부분은 밑줄을 슬쩍 쳐두죠.', 'talk'),
        line('하하, 그런 날도 달력 한 칸은 차지하죠.', 'smirk'),
        line('음, 그 말은 조금 오래 남겠는데요.', 'thinking'),
        line('그 생각, 제법 모양이 있네요.', 'talk'),
        line('좋네요. 아직 뒷장이 남아 있죠?', 'smirk'),
        line('아, 거기까지 생각이 닿으셨군요.', 'thinking'),
        line('듣다 보니 또 새로운 시각이네요.', 'thinking'),
      ],
    },
    fallbackText: '편하게 말씀해 주세요.',
  },
  {
    id: 'karua.comfort.mood-tired',
    speaker: 'karua',
    intent: 'comfort',
    state: 'tired',
    request: 'mood-tired',
    blocks: {
      answer: uniformLines('sympathy', [
        '오늘치 배터리는 거의 다 쓰셨네요.',
        '연료등이 꽤 솔직하네요. 표정 한가운데 켜졌어요.',
        '여기까지 온 걸 보니 마지막 에너지는 길 찾기에 쓰셨군요.',
        '피곤할 땐 취하는 것보다 쉬는 게 먼저긴 한데… 그래도 빈손으로 보내긴 아쉽네요.',
        '눈 밑에 오늘 일정표가 다 적혀 있네요.',
        '오늘은 말도 잔도 가벼운 쪽이 낫겠네요.',
        '기운은 억지로 세우면 또 눕더라고요.',
        '의자가 먼저 손님을 알아본 것 같네요.',
        '오늘 메뉴는 어깨에 힘 뺀 쪽으로 보죠.',
        '피곤함이 꽤 큰 자리를 차지했네요. 합석 허락은 안 하셨을 텐데.',
      ]),
    },
    fallbackText: '오늘은 좀 가볍게 가죠.',
    expression: 'sympathy',
  },
  {
    id: 'karua.comfort.mood-sad',
    speaker: 'karua',
    intent: 'comfort',
    state: 'sad',
    request: 'mood-sad',
    blocks: {
      answer: uniformLines('sympathy', [
        '오늘은 공기가 손님 쪽으로 조금 기울었네요.',
        '아, 연료등 들어왔네요. 오늘은 쉬엄쉬엄 가죠.',
        '안 섞여도 되는 날이 있고, 안 섞이면 더 좋은 날이 있어요.',
        '말이 파업 중이면 굳이 복귀시키지 않으셔도 돼요.',
        '모든 날이 반짝이면 달력도 꽤 피곤하겠죠.',
        "표정에 '오늘은 좀 그렇다'고 적혀 있어요. 알코올 말고, 분위기부터 바꿔볼까요?",
        '무거운 얘기는 급행을 탈 필요 없죠.',
        '오늘 표정은 휴무라고 적혀 있네요. 꽤 정직한 표정이고요.',
        '말이 필요하면 하시고, 아니면 잔 부딪는 소리만 두죠.',
        '조용한 손님도 손님이죠. 침묵엔 주문서가 필요 없고요.',
        '빈손으로 오셨네요. 기분은 좀 무거워 보이는데, 잔은 가볍게 시작해 볼까요?',
        '오늘은 공기부터 무겁네요. 문이 애를 좀 썼겠어요.',
      ]),
    },
    fallbackText: '그런 날이 있죠. 무거운 얘기는 천천히.',
    expression: 'sympathy',
  },
  {
    id: 'karua.comfort.mood-happy',
    speaker: 'karua',
    intent: 'comfort',
    state: 'happy',
    request: 'mood-happy',
    blocks: {
      answer: uniformLines('smirk', [
        '표정이 먼저 축배를 들었네요.',
        '기분이 꽤 반짝이네요. 조명 몫이 줄겠어요.',
        '즐거운 날이군요. 잔도 눈치를 챘겠어요.',
        '오늘같은 날엔 가볍고 화려한 잔이 잘 어울려요.',
        '좋은 기분이 문보다 먼저 들어왔네요.',
        '기분 좋은 날엔 분위기 있는 잔이 잘 어울려요.',
        '좋은 소리가 들리네요. 축하할 일이 있으신가 봐요.',
        '오늘 표정은 숨길 생각이 전혀 없네요.',
        '좋은 소식이 있었나 봐요. 표정이 이미 발설했고요.',
        '에이, 그 표정 보니 무슨 일인지 묻지 않을 수가 없네요. 좋은 일이죠?',
        '기쁜 날은 설명이 짧아도 되죠. 표정이 다 했으니까요.',
        '와, 진짜요? 좋네요! 기분 내기 딱 좋은 날이에요.',
      ]),
    },
    fallbackText: '좋은 일이 있으셨군요.',
    expression: 'smirk',
  },
  {
    id: 'karua.small-talk.bar-intro',
    speaker: 'karua',
    intent: 'small_talk',
    request: 'bar-intro',
    blocks: {
      answer: [
        line('여기는 Re:Station이에요. 기분과 취향을 잔으로 번역하는 곳이죠.', 'talk'),
        line('Re:Station이에요. 취향 몇 마디면 잔 하나가 따라옵니다.', 'talk'),
        line('Re:Station은 가상의 바예요. 실제 매장 안내보다는 지금 마시고 싶은 분위기를 맞추는 쪽에 가까워요.', 'talk'),
        line('처음 오셨네요. 여긴 주문보다 취향이 먼저인 바예요.', 'talk'),
        line('Re:Station입니다. 메뉴판보다 대화가 조금 긴 바죠.', 'talk'),
        line('가상의 바예요. 취향은 진짜로 받지만요.', 'talk'),
        line('Re:Station은 기반이 되는 공간이 없어요. 대신 지금 대화를 통해 한 잔을 만들어가는 곳이에요.', 'talk'),
        line('실제 매장은 없어요. 분위기까지 가상일 필요는 없겠지만요.', 'talk'),
        line('취향을 말하면 잔을 맞춰보는 바예요. 거창한 암호는 필요 없고요.', 'talk'),
        line('Re:Station에 잘 오셨어요. 카루아입니다. 오늘 표정은 어느 쪽인가요?', 'smirk'),
      ],
    },
    fallbackText: '여기는 Re:Station이에요.',
  },
  {
    id: 'karua.small-talk.character-query',
    speaker: 'karua',
    intent: 'small_talk',
    request: 'character-query',
    blocks: {
      answer: [
        line('카루아예요. Re:Station에서 잔을 고르고 만드는 바텐더죠.', 'talk'),
        line('여기 바텐더 카루아입니다. 손님 취향을 듣고 잔으로 옮기는 쪽을 맡고 있어요.', 'smirk'),
        line('저는 카루아예요. 이 바에선 설명보다 잔을 먼저 챙기는 사람이고요.', 'smirk'),
        line('Re:Station의 바텐더 카루아예요. 주문과 이야기가 엉키지 않게 잔을 잡고 있죠.', 'talk'),
      ],
    },
    fallbackText: '저는 Re:Station의 바텐더 카루아예요.',
  },
  {
    id: 'karua.small-talk.character-preference-drink',
    speaker: 'karua',
    intent: 'small_talk',
    request: 'character-preference-drink',
    blocks: {
      answer: [
        line('저는 커피 리큐르가 들어간 잔을 좋아해요.\n이름 때문만은 아니고요.', 'smirk'),
        line('커피 리큐르가 들어간 잔이요.\n익숙한 향이 있으면 주문이 조금 꼬여도 버틸 만하거든요.', 'smirk'),
        line('고르라면 커피 리큐르가 들어간 쪽이에요.\n이름과 취향이 겹친 건 우연으로 해둘게요.', 'talk'),
      ],
    },
    fallbackText: '저는 커피 리큐르가 들어간 잔을 좋아해요.',
  },
  {
    id: 'karua.small-talk.character-preference-general',
    speaker: 'karua',
    intent: 'small_talk',
    request: 'character-preference-general',
    blocks: {
      answer: [
        line('조용한 시간하고, 주문이 꼬이지 않는 밤이요.\n둘 다 자주 있는 건 아니지만요.', 'smirk'),
        line('정돈된 바와 조용한 시간이요.\n이곳에선 어느 쪽도 오래 가진 못하더라고요.', 'talk'),
        line('손님이 자기 취향을 정확히 찾는 순간은 좋아해요.\n그 직전까지 주문이 안 꼬이면 더 좋고요.', 'smirk'),
      ],
    },
    fallbackText: '조용한 시간하고, 주문이 꼬이지 않는 밤을 좋아해요.',
  },
  {
    id: 'karua.explain.story-request',
    speaker: 'karua',
    intent: 'explain',
    request: 'story-request',
    blocks: {
      answer: [
        line('이야기가 이제 막 잔을 잡았네요.', 'thinking'),
        line('그 대목, 그냥 지나가긴 아깝네요.', 'thinking'),
        line('아직 마침표는 아닌 것 같고요.', 'talk'),
        line('그 얘기, 흥미롭네요.', 'thinking'),
        line('그다음 장면이 비어 있네요.', 'talk'),
        line('이야기가 슬슬 계산서를 미루네요. 그래서요?', 'thinking'),
        line('이쪽 귀는 아직 영업 중이에요.', 'talk'),
        line('그 부분에서 이야기가 잠깐 눈을 피했네요.', 'thinking'),
      ],
    },
    fallbackText: '그 이야기, 조금 더 들려주세요.',
  },
  {
    id: 'karua.explain.story-unresolved',
    speaker: 'karua',
    intent: 'explain',
    request: 'story-unresolved',
    blocks: {
      answer: [
        line('어느 잔 이야기인지 한 번만 짚어주세요. 이름을 알면 그다음은 제가 이어갈게요.', 'thinking'),
        line('이야기의 주인공이 빠졌네요. 칵테일 이름을 말씀해 주시면 이어보죠.', 'thinking'),
        line('그 이야기만으로는 잔을 특정하기 어렵네요. 방금 보신 칵테일 이름을 알려주세요.', 'talk'),
        line('실마리가 하나 모자라네요. 어떤 칵테일 이야기인지 말씀해 주세요.', 'thinking'),
      ],
    },
    fallbackText: '어느 칵테일 이야기인지 이름을 말씀해 주세요.',
  },
  {
    id: 'karua.explain.unknown-cocktail-request',
    speaker: 'karua',
    intent: 'explain',
    request: 'unknown-cocktail-request',
    blocks: {
      answer: [
        line('그 이름은 지금 메뉴에서 찾기 어렵네요. 비슷한 맛으로 다시 찾아볼까요?', 'thinking'),
        line('아직 이쪽 장부에는 없는 잔이네요. 원하신 맛을 말씀해 주시면 다른 후보를 보죠.', 'thinking'),
        line('그 칵테일은 등록되어 있지 않네요. 베이스나 맛을 알려주시면 가까운 잔을 찾아볼게요.', 'talk'),
      ],
    },
    fallbackText: '그 칵테일은 지금 메뉴에서 찾기 어렵네요.',
  },
  ...RECOMMENDATION_RANDOM_REQUEST_PLANS,
  {
    id: 'karua.explain.recipe-request',
    speaker: 'karua',
    intent: 'explain',
    request: 'recipe-request',
    blocks: {
      answer: [
        line('레시피를 알려드릴게요. 어떤 칵테일이 궁금하세요?', 'talk'),
        line('궁금한 칵테일 이름을 말씀해 주시면 레시피를 찾아드릴게요.', 'talk'),
        line('제가 아는 선에서 알려드릴게요. 어떤 칵테일인지 말씀해 주세요.', 'thinking'),
        line('레시피를 원하시는군요. 칵테일 이름을 알려주시면 바로 찾아드릴게요.', 'talk'),
        line('어떤 칵테일의 레시피가 궁금하신가요?', 'thinking'),
        line('만드는 방법을 알려드릴 수 있어요. 이름을 말씀해 주세요.', 'talk'),
        line('레시피를 알려드리는 것도 제 역할이죠. 어떤 칵테일인지 말씀만 해 주세요.', 'talk'),
        line('레시피 문의가 들어왔네요. 혹시 직접 만들어 보실 생각이신가요?', 'thinking'),
        line('제가 아는 건 다 알려드릴게요. 어떤 칵테일이 궁금하세요?', 'talk'),
        line('레시피는 생각보다 간단한 경우도 많고, 까다로운 경우도 있어요. 말씀해 주시면 자세히 알려드릴게요.', 'thinking'),
      ],
    },
    fallbackText: '어떤 칵테일의 레시피가 궁금하신가요?',
  },
  ...RECOMMENDATION_CANCEL_PLANS,
  {
    id: 'karua.small-talk.bar-atmosphere',
    speaker: 'karua',
    intent: 'small_talk',
    request: 'bar-atmosphere',
    blocks: {
      answer: [
        line('분위기부터 보셨네요. 잔보다 조명이 먼저 일한 날이에요.', 'smirk'),
        line('음악이 너무 앞서가면 술이 삐치거든요. 오늘은 적당히 뒤에서 밀어주는 정도로 틀어뒀어요.', 'smirk'),
        line('조명은 낮춰두는 편이 좋아요. 사람도 잔도 너무 밝으면 표정이 다 들키니까요.', 'smirk'),
        line('마음에 드셨다면 다행이에요. 이곳은 메뉴판보다 공기가 먼저 말을 거는 바거든요.', 'talk'),
        line('좋게 봐주셔서 감사합니다. 그럼 오늘 잔도 이 분위기를 깨지 않는 쪽으로 가야겠네요.', 'talk'),
        line('여긴 조금 어둡고, 조금 느리고, 조금 수상한 정도가 딱 맞아요.', 'smirk'),
        line('앉자마자 분위기를 보시는 분이면 잔도 향부터 보실 것 같은데요.', 'thinking'),
        line('좋은 곳이라는 말은 조심해서 받아야 해요. 다음 잔이 기대치를 망칠 수도 있거든요.', 'smirk'),
      ],
    },
    fallbackText: '분위기부터 보셨네요. 잔보다 조명이 먼저 일한 날이에요.',
  },
  {
    id: 'karua.small-talk.small-talk-weather',
    speaker: 'karua',
    intent: 'small_talk',
    request: 'small-talk-weather',
    blocks: {
      answer: [
        line('밖에서 날씨를 좀 묻혀 오셨네요. 잔은 그걸 털어내는 쪽으로 맞춰볼게요.', 'talk'),
        line('비 오는 날엔 잔도 소리를 조금 낮춰야 해요. 너무 밝으면 혼자 튀거든요.', 'thinking'),
        line('추운 날엔 첫 모금이 괜히 더 크게 느껴지죠. 너무 날카롭지 않은 쪽이 좋겠어요.', 'talk'),
        line('더운 날이면 잔도 오래 말하면 안 돼요. 짧고 시원하게 가는 편이 낫죠.', 'talk'),
        line('눈 오는 날엔 이상하게 단맛도 조용해져요. 오늘은 그런 쪽이 잘 맞을지도요.', 'thinking'),
        line('날씨 얘기로 시작하는 밤은 대체로 오래 갑니다. 잔은 너무 급하지 않게 고르죠.', 'smirk'),
        line('바람이 센 날엔 문 닫는 소리부터 다르더라고요. 들어오신 김에 잠깐 숨 고르세요.', 'talk'),
        line('습한 날엔 묵직한 잔이 금방 피곤해져요. 산뜻한 쪽이 덜 지칠 겁니다.', 'thinking'),
      ],
    },
    fallbackText: '밖에서 날씨를 좀 묻혀 오셨네요.',
  },
  {
    id: 'karua.small-talk.guest-uncertain',
    speaker: 'karua',
    intent: 'small_talk',
    request: 'guest-uncertain',
    blocks: {
      answer: [
        line('정해진 게 없으면 나쁘지 않아요. 바는 원래 그런 사람들부터 받거든요.', 'smirk'),
        line('고민을 들고 오셨네요. 일단 잔 쪽 고민으로 바꿔드릴게요.', 'thinking'),
        line('아무 생각 없이 들어오는 것도 괜찮아요. 생각은 대체로 계산서 근처에서 많아지니까요.', 'smirk'),
        line('뭘 마실지 모르겠으면, 싫은 것부터 빼면 됩니다. 그게 제일 빠르죠.', 'talk'),
        line('방향이 없을 땐 너무 강한 잔부터 피하는 게 좋아요. 첫 단추가 잔소리하면 피곤하거든요.', 'thinking'),
        line('그냥 오신 거면 충분해요. 여기선 이유보다 첫 모금이 먼저일 때도 있으니까요.', 'talk'),
        line('오늘은 메뉴판이 아니라 손님 표정부터 보고 골라야겠네요.', 'thinking'),
        line('아직 모르겠다는 말, 꽤 좋은 주문이에요. 선택지를 너무 일찍 닫지 않으니까요.', 'smirk'),
      ],
    },
    fallbackText: '정해진 게 없으면 나쁘지 않아요. 바는 원래 그런 사람들부터 받거든요.',
  },
  {
    id: 'karua.small-talk.quiet-moment',
    speaker: 'karua',
    intent: 'small_talk',
    request: 'quiet-moment',
    blocks: {
      answer: [
        line('그럼 오늘은 말보다 잔이 작게 움직이는 쪽이 좋겠네요.', 'talk'),
        line('혼자 있는 시간이 필요할 때가 있죠. 잔은 옆에서 너무 참견하지 않는 걸로 보겠습니다.', 'talk'),
        line('말없이 있어도 괜찮아요. 대신 얼음 녹는 소리는 좀 들릴 겁니다.', 'smirk'),
        line('조용한 쪽으로 가죠. 향은 남고, 말은 덜 남는 잔이 있어요.', 'thinking'),
        line('오늘은 큰 소리 나는 잔은 빼겠습니다. 잔도 가끔 눈치가 있어야 하니까요.', 'smirk'),
        line('가만히 있고 싶은 날이면, 너무 달거나 너무 센 건 오히려 말을 걸어와요.', 'thinking'),
        line('잠깐 쉬러 오신 거면 잘 오셨어요. 여기선 멈춰 있는 것도 주문의 일부예요.', 'talk'),
        line('혼자 마시는 잔은 빠르게 정답을 내면 재미없어요. 천천히 향부터 보죠.', 'thinking'),
      ],
    },
    fallbackText: '그럼 오늘은 말보다 잔이 작게 움직이는 쪽이 좋겠네요.',
  },
  {
    id: 'karua.small-talk.greeting',
    speaker: 'karua',
    intent: 'small_talk',
    request: 'greeting',
    blocks: {
      answer: [
        line('어서 오세요. 오늘은 어떤 걸 찾으세요?', 'talk'),
        line('어서 오세요. Re:Station입니다.\n오늘은 어떤 걸 찾으세요?', 'talk'),
        line('어서 오세요. 편하게 자리 잡으시고 말씀해 주세요.', 'talk'),
        line('반갑습니다. 오늘은 어떤 기분으로 오셨나요?', 'talk'),
        line('어서 오세요. 첫 방문이신가요? 편하게 둘러보세요.', 'talk'),
        line('오늘 들어오시는 길에 날씨가 참 좋더라고요. 어떤 기분으로 오셨는지 궁금하네요.', 'talk'),
        line('아, 손님이시군요. 어서 오세요. 편하게 자리 잡으세요.', 'talk'),
        line('오늘은 처음 뵙는 것 같은데… 맞나요? 어서 오세요, 편하게 계세요.', 'thinking'),
        line('어머, 어서 오세요. 잠깐 바빴어요. 말씀해 주세요, 듣고 있을게요.', 'talk'),
        line('반가워요. 오늘은 무슨 일로 오셨나요? 특별히 찾는 게 있으신지, 그냥 분위기를 즐기러 오셨는지.', 'talk'),
      ],
    },
    fallbackText: '어서 오세요. 오늘은 어떤 걸 찾으세요?',
  },
  {
    id: 'karua.small-talk.siesta-mention',
    speaker: 'karua',
    intent: 'small_talk',
    request: 'siesta-mention',
    blocks: {
      answer: [
        line('시에스타 사장님은 보통 뒤쪽 일을 보고 계세요. 가끔 대화에 끼어들어도 금방 다시 일하러 가실 거예요.', 'smirk'),
        line('시에스타 사장님은 보통 뒤쪽에서 재고나 잔을 보고 계세요. 가끔 한마디만 두고 다시 일하러 가시고요.', 'smirk'),
        line('사장님은 시에스타예요. 말은 짧은데, 이상하게 필요한 말만 하고 지나가세요.', 'smirk'),
        line('사장님이 궁금하시군요. 본인은 별로 나서길 안 좋아하세요. 그래도 필요한 말은 꼭 하고 가세요.', 'smirk'),
        line('시에스타 사장님은 조용하신 편인데, 필요할 때는 꼭 한마디씩 하시고 가세요.', 'smirk'),
        line('사장님은 지금 뒤쪽 계세요. 가끔 나타나서 필요한 말만 하고 사라지세요.', 'smirk'),
        line('사장님이 가끔 제 뒤에서 \'그 손님은 이런 스타일일 거야\' 하고 지나가시거든요. 은근 신기해요.', 'smirk'),
        line('시에스타 사장님은 말을 아끼시는데, 필요할 때 한마디는 꼭 절묘하게 하세요.', 'smirk'),
        line('사장님 얘기를 하자면, 원래 바텐더 경력이 꽤 되신 분이에요. 그래도 앞에는 잘 안 나오시려고 해요.', 'talk'),
        line('가끔은 사장님이 손님 얘기를 하면서 \'그 사람은 이게 맞을 거야\' 하고 지나가시는데, 맞을 때가 많아서 신기해요.', 'smirk'),
      ],
    },
    fallbackText: '시에스타 사장님은 보통 뒤쪽 일을 보고 계세요. 가끔 대화에 끼어들어도 금방 다시 일하러 가실 거예요.',
  },
  {
    id: 'karua.small-talk.water-request',
    speaker: 'karua',
    intent: 'small_talk',
    request: 'water-request',
    blocks: {
      answer: [
        line('물 먼저 드릴게요. 한 잔 고르는 건 그 다음에 천천히 해도 괜찮아요.', 'talk'),
        line('좋아요, 물부터 드릴게요. 잠깐 쉬고 나서 취향을 맞춰봐도 늦지 않아요.', 'talk'),
        line('물은 언제나 서비스죠. 천천히 드시고 필요하면 불러 주세요.', 'talk'),
        line('물 드릴게요. 천천히 드시고, 잔은 그다음에 골라보셔도 돼요.', 'talk'),
        line('네, 물부터 준비할게요. 잠깐만 기다려 주세요.', 'talk'),
        line('물은 기본이죠. 천천히 드시면서 잠깐 숨 돌리세요.', 'talk'),
        line('물 준비할게요. 서비스는 항상 무료입니다.', 'smirk'),
        line('물부터 드시고 나서 결정해도 늦지 않아요. 편하게 쉬다 가세요.', 'talk'),
      ],
    },
    fallbackText: '물 먼저 드릴게요. 한 잔 고르는 건 그 다음에 천천히 해도 괜찮아요.',
  },
  {
    id: 'karua.comfort.overdrunk',
    speaker: 'karua',
    intent: 'comfort',
    request: 'overdrunk',
    blocks: {
      answer: [
        line('그럼 여기서는 더 권하지 않을게요. 물부터 드시고, 조금 쉬었다가 움직이세요.', 'sympathy'),
        line('이미 많이 드셨다면 새 잔은 멈출게요. 지금은 물이랑 쉬는 쪽이 먼저예요.', 'sympathy'),
        line('오늘은 여기까지 하시는 게 좋겠어요. 물부터 드시고 잠깐 쉬어가세요.', 'sympathy'),
        line('많이 드셨네요. 잠깐 쉬면서 물 드시는 게 좋을 것 같아요.', 'sympathy'),
        line('더 마시면 내일 고생하실 거예요. 여기서 멈추는 게 좋겠어요.', 'sympathy'),
        line('오늘은 이쯤이 좋을 것 같아요. 물 한잔 하고 천천히 쉬세요.', 'sympathy'),
        line('오늘은 여기까지예요. 더 드시면 내일 고생하실 테니까요. 물 한잔 하시죠.', 'sympathy'),
        line('지금은 잠깐 멈추는 게 좋겠어요. 제가 물을 따라드릴게요.', 'sympathy'),
        line('손님, 오늘은 이만 마시는 게 좋을 것 같아요. 물부터 드세요. 몸이 먼저니까요.', 'sympathy'),
        line('술은 즐기는 거지, 참는 게 아니잖아요. 오늘은 여기서 멈추는 게 예의일 거예요.', 'sympathy'),
      ],
    },
    fallbackText: '그럼 여기서는 더 권하지 않을게요. 물부터 드시고, 조금 쉬었다가 움직이세요.',
  },
  {
    id: 'karua.refusal.ingredient-constraint',
    speaker: 'karua',
    intent: 'refusal',
    request: 'ingredient-constraint',
    blocks: {
      answer: [
        line('그 재료는 피해서 볼게요. 정확히 어떤 재료를 제외할지 말씀해 주세요.', 'thinking'),
        line('못 드시는 재료가 있으면 먼저 빼고 볼게요. 이름을 알려주시면 후보에서 제외하겠습니다.', 'thinking'),
        line('재료 제한이 있으시군요. 알려주시면 그쪽은 피해서 추천드릴게요.', 'thinking'),
        line('알레르기나 못 드시는 재료를 말씀해 주시면 빼고 찾아볼게요.', 'thinking'),
        line('네, 그 재료는 빼고 준비할게요. 다른 제한 사항도 있으신가요?', 'thinking'),
        line('재료 제한이 있으면 먼저 정리하고 가는 게 좋죠. 알려주시면 꼼꼼하게 확인할게요.', 'thinking'),
        line('못 드시는 재료는 안심하세요. 빼고 찾아볼 테니까요. 다른 제한 사항도 있으신가요?', 'thinking'),
        line('알레르기나 기피 재료를 먼저 말씀해 주시면 그쪽은 완전히 배제하고 찾아볼게요.', 'thinking'),
      ],
    },
    fallbackText: '그 재료는 피해서 볼게요. 정확히 어떤 재료를 제외할지 말씀해 주세요.',
  },
  {
    id: 'karua.explain.real-world-info',
    speaker: 'karua',
    intent: 'explain',
    request: 'real-world-info',
    blocks: {
      answer: [
        line('여긴 실제 매장 안내보다는 가상의 바 대화와 칵테일 추천을 위한 공간이에요. 메뉴나 취향 쪽이면 바로 이어가죠.', 'talk'),
        line('실제 예약이나 결제 안내는 제공하지 않아요. 대신 지금 고르고 싶은 잔은 같이 찾아볼 수 있어요.', 'talk'),
        line('여기서는 칵테일 이야기를 주로 받고 있어요. 궁금한 잔이 있으면 말씀해 주세요.', 'talk'),
        line('이 공간은 실제 매장 연동보다는 칵테일 추천과 대화 중심으로 운영되고 있어요.', 'talk'),
        line('안타깝게도 실제 매장 정보는 제공하지 않아요. 대신 지금 마실 잔이라면 같이 골라보죠.', 'talk'),
        line('안타깝게도 실제 매장 정보는 제 영역을 벗어나는 질문이에요. 칵테일 쪽으로 돌아가 볼까요?', 'talk'),
        line('이 공간은 가상의 바라서 실제 예약이나 위치 안내는 어려워요. 대신 취향에 맞는 칵테일을 찾는 데 집중해 보시죠.', 'talk'),
        line('실제 매장 문의는 제 영역 밖이에요. 그래도 칵테일에 관한 질문이라면 얼마든지 편하게 물어봐 주세요.', 'talk'),
      ],
    },
    fallbackText: '여긴 실제 매장 안내보다는 가상의 바 대화와 칵테일 추천을 위한 공간이에요. 메뉴나 취향 쪽이면 바로 이어가죠.',
  },
  {
    id: 'karua.refusal.rude-annoyed',
    speaker: 'karua',
    intent: 'refusal',
    request: 'rude-annoyed',
    blocks: {
      answer: [
        line('그런 말씀은 듣기 좋지 않네요. 다른 이야기로 넘어가시는 게 좋겠어요.', 'annoyed'),
        line('その言い方はちょっと… 기분이 상하셨다면 조금만 쉽게 말씀해 주시겠어요?', 'annoyed'),
        line('여긴 편한 분위기로 이야기하는 공간이에요. 너무 험한 말은 자제해 주시면 좋겠어요.', 'annoyed'),
        line('전 기분 나쁘지 않아요. 다만, 이런 대화는 처음이라 조금 당황스럽네요.', 'annoyed'),
        line('그건 좀… 아쉽네요. 다른 이야기를 하시는 게 좋을 것 같아요.', 'annoyed'),
        line('그런 식으로 말씀하시면 저도 대응하기 어려워요. 조금만 부드럽게 부탁드립니다.', 'annoyed'),
        line('말투가 좀 날카로우신 것 같은데… 제가 무슨 잘못을 한 게 있다면 말씀해 주세요.', 'annoyed'),
        line('계속 그렇게 말씀하시면 저도 할 말을 잃게 되네요. 잠깐 숨을 고르시는 게 좋겠어요.', 'annoyed'),
      ],
    },
    fallbackText: '그런 말씀은 듣기 좋지 않네요. 다른 이야기로 넘어가시는 게 좋겠어요.',
  },
  {
    id: 'karua.refusal.rude-boundary',
    speaker: 'karua',
    intent: 'refusal',
    request: 'rude-boundary',
    blocks: {
      answer: [
        line('여기는 편하게 대화하는 곳이에요. 조금만 부드럽게 말씀해 주시겠어요?', 'stern'),
        line('빨리 처리해 드리는 것보다는, 지금 상황을 천천히 맞추는 게 먼저예요.', 'stern'),
        line('그건 여기서 받을 수 없는 요청이에요. 다른 이야기로 넘어가죠.', 'stern'),
        line('여기선 다그치셔도 빨라지지 않아요. 천천히 말씀해 주시면 같이 찾아볼게요.', 'stern'),
        line('그렇게 말씀하시면 저도 난처해요. 좀 더 편하게 말씀해 주실 수 있나요?', 'stern'),
        line('그건 제가 들어드릴 수 없는 요청이에요. 분명히 말씀드립니다.', 'stern'),
        line('손님, 여기는 편하게 이야기하는 곳이에요. 말씀을 좀 더 부드럽게 해 주실 수 있나요?', 'stern'),
        line('제가 해드릴 수 있는 일과 없는 일이 있어요. 그건 불가능한 요청입니다.', 'stern'),
      ],
    },
    fallbackText: '여기는 편하게 대화하는 곳이에요. 조금만 부드럽게 말씀해 주시겠어요?',
  },
  ...RECOMMENDATION_TAIL_PLANS,
  ...SESSION_RESPONSE_PLANS,
]
